
server:
  port: 8003

eureka:
  instance:
    hostname: eureka-server3   # eureka服务端的实力名称
  client:
    fetch-registry: false # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false  # false表示自己不需要向注册中心注册自己
    serviceUrl:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server2:8002/eureka/