spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 39.100.107.127:9300
      cluster-name: elasticsearch
  elasticsearch:
    jest:
      uris: http://39.100.107.127:9200
