server:
  port: 5005


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1  #最大阻塞等待时间(负值表示没有限制)
        max-idle: 10  #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
    lettuce:
      shutdown-timeout: 1000  #连接超时时间(毫秒)

